Add Desktop size compatibility
shubhambhoyar077/portfolio pull request #4
Opened 2023-01-18 16:08 UTC by shubhambhoyar077

1) Add desktop and tablet size compatibility.
2) Use media query for size compatibility.
3) Fix README file.

<b>Question</b>
1) Mobile and Desktop figma template have different work template shown as follow:-

<b>Desktop</b>

![Screenshot from 2023-01-18 21-28-48](https://user-images.githubusercontent.com/70534992/213225331-c333bad6-eb00-4a76-90bd-e3201e139639.png)

<b>Mobile</b>

![Screenshot from 2023-01-18 21-29-08](https://user-images.githubusercontent.com/70534992/213225385-af407657-28ec-4e01-b012-4df8e2c9b494.png)

Which one should we use? (<b>I have use mobile work template with buttons for desktop.)

2023-01-18 19:03 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @shubhambhoyar077 , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Indeed you did a great job but still there few things that need to be addressed to get you to the next milestone.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

**_Check the comments below to view the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 19:09 UTC, ABDULALI3468 commented on css/style.css
> +  }
There exist a big difference between your Design and Figma design consider reviewing your design including `flex-direction, the width of elements and styles` so it can stand out for your self as your portfolio is representing you .I am attaching screenshots below for further clearance:

FIGMA DESIGN:

![image](https://user-images.githubusercontent.com/94223367/213272123-fac21194-943c-490c-a5b8-1e0fd4ec1f6f.png)


YOUR DESIGN:

![image](https://user-images.githubusercontent.com/94223367/213272148-cf14570b-3ba6-4dcb-a81e-b880c7d730fc.png)

2023-01-19 08:43 UTC, shubhambhoyar077 commented on index.html
> +            </div>
Fixed

2023-01-19 08:43 UTC, shubhambhoyar077 commented on index.html
> +                        <p class="project-description">A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the
Done

2023-01-19 08:44 UTC, shubhambhoyar077 commented on index.html
> +                        <button type="button" class="half-btn">See Project</button>
Done.

2023-01-19 08:45 UTC, shubhambhoyar077 commented on css/style.css
Fix button, size, font family and margin as per figma template2

2023-01-19 08:46 UTC, shubhambhoyar077 commented on css/style.css
> +  }
Done

2023-01-19 08:46 UTC, shubhambhoyar077 commented on css/style.css
>  }
Fixed

2023-01-19 08:47 UTC, shubhambhoyar077 commented on css/style.css
> +  }
Improve design

2023-01-19 09:08 UTC, OyePriscilla approved these changes
Hi @shubhambhoyar077 😄, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
✔️Made the required changes👍
✔️No linter errors👍
✔️GitHub flow observed👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 09:08 UTC, OyePriscilla commented on css/style.css
> +    font-family: 'Crete Round', sans-serif;
- [optional] You've done well by adding the appropriate font family (Crete Round), but it is not effective because you've not imported it (either to your CSS or HTML file). You can read through this [short tutorial](https://www.w3docs.com/snippets/css/how-to-import-google-fonts-in-css-file.html) in order to achieve that. I implore you to do this before you move on to the next milestone. Thanks. 👍

2023-01-19 09:39 UTC, merged